name: gurucoolv1
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  platform: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  shared_preferences: 2.0.13
  cloud_firestore: ^3.1.10
  firebase_messaging: ^11.2.11
  circular_check_box: ^1.0.4
  firebase_core: ^1.13.1
  percent_indicator: ^4.0.0
  confetti: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/gurucool.png
    - assets/circular_kids.png
    - assets/vertical_kids.png
    - assets/background.jpg
    - assets/frame.jpg
    - assets/sign_board.png
    - assets/food5.jpg
    - assets/activity.png
    - assets/vocab.png
    - assets/point1.png
    - assets/point2.png
    - assets/point3.png
    - assets/scenery.png
    - assets/goal.png
    - assets/quizz.jpg
    - assets/books.png
    - assets/finish.png

  fonts:
    - family: Amatic
      fonts:
          - asset: assets/AmaticSC-Regular.ttf
          - asset: assets/Amatic-Bold.ttf

    - family: Alpha
      fonts:
        - asset: assets/alpha_echo.ttf

    - family: FFF
      fonts:
        - asset: assets/FFF_Tusj.ttf

  uses-material-design: true

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
